import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Monoton } from "next/font/google";

const monoton = Monoton({
  subsets: ["latin"],
  weight: "400",
  style: ["normal"],
  variable: "--font-monoton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monoton.variable}`}>
        <div className="container">
          <div className={"wrapper"}>{children}</div>
        </div>
      </body>
    </html>
  );
}
